### ISSUE TITLE
Explore Pandas' BigQuery support

### ISSUE THREAD

**Issue by beriberikix** [GoogleCloudPlatform/google-cloud-python#125]
From the BigQuery folks, [Pandas](http://pandas.pydata.org/) is really popular among users. There is [experimental support for BigQuery](http://pandas.pydata.org/pandas-docs/stable/io.html#google-bigquery-experimental) but it would be useul to see how gcloud and Pandas could be more compatible.

Low priority, not assigned to a milestone for now.

**Comment by dwmclary** [comment]
Because pandas does not keep feature sync with BigQuery, I think what we'd like to see here is at the ability to receive row-results as a pandas DataFrame.

**Comment by tswast** [comment]
Note that Panda's native support for BigQuery has been pulled into the pandas-gbq package (code: https://github.com/pydata/pandas-gbq)

I've been watching that repo begun helping with some maintenance tasks. It might make sense to adopt that package as the official support for Pandas rather than building something here.

**Comment by dhermes** [comment]
:+1: Thanks for the heads up Tim! :panda_face:

**Comment by lukesneeringer** [comment]
I agree with @tswast's plan.
