### ISSUE TITLE
Should we URL quote subscription names

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#1507]
@tseaver I tried to use

``` python
t = client.topic('foo')
s = t.subscription('bar with space')
```

and got a strange error. Should we forbid subscription names that don't adhere or manually escape them for users? I wrote a docstring edit but wanted to discuss before sending a PR

``` diff
diff --git a/gcloud/pubsub/subscription.py b/gcloud/pubsub/subscription.py
index e3da8a0..8c54d39 100644
--- a/gcloud/pubsub/subscription.py
+++ b/gcloud/pubsub/subscription.py
@@ -26,7 +26,10 @@ class Subscription(object):
     https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions

     :type name: string
-    :param name: the name of the subscription
+    :param name: the name of the subscription. Must start with a letter, and
+                 contain only letters, numbers, dashes, underscores, periods,
+                 tildes, plus or percent signs. It must be between 3 and 255
+                 characters in length, and it must not start with ``goog``.

     :type topic: :class:`gcloud.pubsub.topic.Topic`
     :param topic: the topic to which the subscription belongs..
```

**Comment by tseaver** [comment]
I'm assuming you mean [URL quoting](https://docs.python.org/2/library/urllib.html#urllib.quote)?.  I'd prefer that we just document the expected format, preferably by pointing to the API docs (I looked at `project.subscriptions` and `project.subscriptions.create`, and couldn't find the constraint specified).

**Comment by dhermes** [comment]
:+1: Yes I meant that, sorry.

**Comment by dhermes** [comment]
The constraint I mentioned is from the [`topics.create`][1] doc. Also just searching for `255` in the [discovery doc][2] turns up lots of mentions.

[1]: https://cloud.google.com/pubsub/reference/rest/v1/projects.topics/create
[2]: https://www.googleapis.com/discovery/v1/apis/pubsub/v1/rest

**Comment by tseaver** [comment]
Hmm, I didn't look at the "Try It!" section for specification, silly me.  `subscriptions.create` has it, too!

**Comment by tseaver** [comment]
Anyway, I'm still -1 on DWIMing the invalid-name-with-spaces to the urlquoted form.  Maybe we can Zawinski the names ahead of time (of course, then we have to worry about drift between our regex and the backend's constraints).

**Comment by dhermes** [comment]
Cool. At the very least we should update the docstrings

**Comment by lukesneeringer** [comment]
Hello! :-)
First, a _mea culpa_; I have not done as good of a job at keeping up with issues as I should have. If you are getting this (I admit it) cut and paste, it is likely because your issue sat for too long.

In this case, I have been in the process of making a radical update to the PubSub library (#3637) to add significant performance improvements and a new surface, which we hope to launch soon. As such, I am clearing out issues on the old library. It is my sincere goal to do a better job of being on top of issues in the future.

As the preceding paragraph implies, I am closing this issue. If the revamped library does not solve your issue, however, please feel free to reopen.

Thanks!
