### ISSUE TITLE
Bigtable `PartialRowsData` is not an iterable.

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#1812]
It appears to me that if I want to scan through all rows of a Bigtable, [`Table.read_rows()`](https://googlecloudplatform.github.io/gcloud-python/stable/bigtable-table.html#gcloud.bigtable.table.Table.read_rows) is the function to use. This returns a [PartialRowsData](https://googlecloudplatform.github.io/gcloud-python/stable/bigtable-row-data.html#gcloud.bigtable.row_data.PartialRowsData).

Why is `PartialRowsData` not an iterable? I'd like to consume all the rows for a "hello bigtable" sample by iterating through them. Something like

```
print('Scan for all greetings:')
for row in table.read_rows():
    print(row.cells[COLUMN_FAMILY_NAME][COLUMN_NAME.encode('UTF-8')][0].decode('UTF-8'))
```

Instead, it appears that I need to use a while loop and watch a dictionary that gets populated. I think this means that even if I don't need to store all the rows in memory at once, they still do. That's both inefficient and not following Python idioms (of generators / iterables).

**Comment by dhermes** [comment]
Taking a [peek at `PartialRowsData.consume_next()`][1], it's because of the nature of the Bigtable API. The actual stream returned from the API may have partial results for a row, hence we need to build it up to get a complete answer. I agree this is memory hungry and this was something I worried about (tried to track down old discussions, can't find any right now).

You don't need to use a while loop, you can just use

```python
partial_rows = table.read_rows()
partial_rows.consume_all()
```

Maybe we should make this clearer in the [Data API doc][2]?

[1]:https://github.com/GoogleCloudPlatform/gcloud-python/blob/8dd7fefeac9ecf08c10b4da1edb37caba16b71c6/gcloud/bigtable/row_data.py#L287-L302
[2]: https://googlecloudplatform.github.io/gcloud-python/stable/bigtable-data-api.html

**Comment by tswast** [comment]
Yeah, it could could definitely be clearer in the docs. I'll see if I can improve them at all as I work on the bigtable "hello world".

I can imagine `consume_all()` being super memory hungry, so I would still like an easy way to consume in a specified batch size.

@dhermes What do you think about adding an `iterrows()` function/generator to `PartialRowsData` that yields a `(key, row)` tuple and deletes that row from `rows` after calling `consume_next()`?

**Comment by dhermes** [comment]
I'm 100% for making this **actually** stream results instead of storing them in a dictionary. I just don't know what the implications are of giving users partially built results due to chunking. Could you sit down with someone on the eng team for a chat / sanity check?

**Comment by tswast** [comment]
I've thought about this some more (and read the source code). I'm starting to think the current implementation is the only way it can work, at least if we want to provide full rows in the client.

Maybe we could return a partial row and then later another partial row with the same key? I'm wondering if that behavior would be more intuitive than filling the client's memory. Probably not, actually.

**Comment by dhermes** [comment]
Thanks for giving it some thought!

**Comment by flunderpero** [comment]
AFAICS all the other APIs (Go and Java) provide a true iterator-interface. And it is really *needed* in Python, too. Otherwise a lot of use-case are simply impossible to implement.

It should be as simple as: Whenever the state switches to `NEW_ROW` we know that we have read a complete row before that and we can `yield` that (assuming the iterator is written as a generator). This seems to be what the [Go-code](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigtable/reader.go) is doing.

**Comment by dhermes** [comment]
Thanks for bringing this to our attention @flunderpero. Maybe I misunderstand `CellChunk.row_status`. When you say `NEW_ROW`, you are referring to `commit_row`?

ISTM that you are describing a temporary dict that we pop (and yield) from every time `commit_row` is encountered? Essentially the same underlying data structure that currently exists, except we don't allow it to grow without bound, since we pop a given row once the API tells us to move on.

[1]: https://github.com/googleapis/googleapis/blob/d3e2ebbb857e061e4c0bb632fe8da2a888cf91cf/google/bigtable/v2/bigtable.proto#L150-L158

**Comment by garye** [comment]
This is something the Bigtable team would like to see in the API. I'm happy to sign up to do the work, which I believe could be making `PartialRowsData` iterable with the method @dhermes describes above.

**Comment by garye** [comment]
The motivation here is that, while one row can be a maximum of [256MiB](https://github.com/googleapis/googleapis/blob/master/google/bigtable/v2/data.proto#L27), reading the entire result of a `read_rows` call with `consume_all` could quickly lead to memory issues on the client.

**Comment by dhermes** [comment]
Works for me @garye.

@lukesneeringer WDYT (re: prioritization)?

**Comment by zakons** [comment]
BigTable: Adding a row generator on a table. #4679 is in final stages of test / review.

**Comment by chemelnucfin** [comment]
Hello, feature requests will now be tracked in the project [Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867160).  I will close this issue now, please feel free to continue to address any issues/concerns here.
