### ISSUE TITLE
Documentation site generation strategy

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2043]
@dhermes brought up some questions about this in #2039.

Potentially using `sphinx-apidoc` to create an index that is the source of truth to build the site JSON from. Probably a lot more things as well.

**Comment by dhermes** [comment]
To clarify, I was not suggesting that we use `sphinx-apidoc` to create the index, but rather we move [our Sphinx docs][1] to using `sphinx-apidoc` so that the only documentation lives in modules. This way the two doc strategies will be closer to the same. (This doesn't cover our usage docs, especially those that live in multiple files.)

[1]: http://gcloud-python.readthedocs.io/en/latest/
