### ISSUE TITLE
Use unittest.mock / mock instead of _Monkey

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2142]
This may be a non-trivial project but it makes our unit tests look more familiar to the average Python dev. We can in the short-term just require new mocks to be written with `unittest.mock`

When we started this project in 2014 I had never used `unittest.mock` / [`mock`](https://pypi.python.org/pypi/mock) but have used it extensively in `oauth2client` and find it is really flexible (and involves writing less code than we do when mocking).

Assigning to @tseaver because he has probably thought about this more than I have.

**Comment by tseaver** [comment]
After some discussion with my similarly-curmudgeonly partner @mcdonc, I'm +0 on the use of [`mock.patch`](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch) instead of our [`_Monkey`](https://github.com/GoogleCloudPlatform/gcloud-python/blob/fd0e6bf7aac1f4373c64d8e76552d395a1dbf279/gcloud/_testing.py#L18) class.  Caveats:

- I don't like the decorator style in general, and would prefer that we use `mock.patch` as a context manager.
- `mock-patch.multiple` is most like our current `_Monkey`, and would be the least disruptive replacement.

I strongly dislike the [`mock.MagicMock`](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.MagicMock) weirdness, as well as any other features which "avoid typing" in tests at the expense of comprehensibility.  I've literally quit contributing to more than one project where `mock` was used with abandon for that reason:  "Unit tests are no place for cleverness."

**Comment by jonparrott** [comment]
If we do switch to pytest as runner, we can take advantage of pytest's `monkeypatch` fixture. This could eliminate the need for `_Monkey`.

Use of `mock.Mock()` and `mock.patch()` is a separate case. I think there should be no reason to discourage people from using them where appropriate. Decorator style reads better with pytest-style test functions, but I agree that context-manager style reads better with `unittest`'s test classes.

**Comment by dhermes** [comment]
This is still an issue, `_Monkey` is around in places and should be removed.
