### ISSUE TITLE
Stop using GOOGLE_CLOUD_TESTS_PROJECT_ID

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2263]
Related to #2259.

With the project ID from `GOOGLE_APPLICATION_CREDENTIALS` support added by @daspecster, we don't need to specify the project ID any longer. Though I may be wrong on this, e.g. if some API doesn't use credentials but does use a project ID.

**Comment by rimey** [comment]
Can you say a little more about what you have in mind and point to the changes by @daspecster that you mentioned?

For a number of reasons, it's important that the automated system tests continue to associate their RPCs with your own GCP project (rather than using a shared project ID built into the auth library).

- It gives you control over your RPC quota limits.
- It lets you monitor your RPC quota usage.
- It gives you control over which APIs are enabled.
- It enables Google on-call engineers to associate the RPCs with this project in case there are issues that need to be investigated.

**Comment by rimey** [comment]
I might be worried about nothing. With GOOGLE_APPLICATION_CREDENTIALS pointing at credentials for a service account, the project owning that service account will be the issuing project for the RPCs, and all will be well.

**Comment by dhermes** [comment]
@rimey Check out the [implementation][1]. In particular, `_file_project_id()` gets the project ID from the `GOOGLE_APPLICATION_CREDENTIALS` file (which is already the same as the one we set in tests).

----

> rather than using a shared project ID built into the auth library

This doesn't exist (and can't really for most requests).

----

> I might be worried about nothing. With GOOGLE_APPLICATION_CREDENTIALS pointing at credentials for a service account, the project owning that service account will be the issuing project for the RPCs, and all will be well.

Exactly

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/1f75bde2fe63420d9687610762920f8e5e6bd65c/google/cloud/_helpers.py#L290

**Comment by rimey** [comment]
Thanks. This all sounds good.

> > rather than using a shared project ID built into the auth library

> This doesn't exist (and can't really for most requests).

I should have said built into the Cloud SDK.
