### ISSUE TITLE
User indicates very high Pub/Sub publish  average latency for gcloud-python

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-python#2301]
Hey, Gcloud-python team, 

I have a user who was left disappointed. From an extract: 
"With Google’s gcloud python library, we are seeing avg latencies around 400ms publishing tiny messages. This is unacceptable so we tried the experimental RPC library in both python and go, and see average latencies around 120ms."  Do we have any idea where the discrepancy might be coming from?  Glad to offer some more detail -- contact me directly @google.com if possible.

Kir

**Comment by dhermes** [comment]
We have gRPC support as well, depending on what version they are using. The latency would be from the network, not from the library, but the 400ms might not all be latency.

For example, there are blocking calls that may wait longer, though we don't use any explicit sleeps, so that would indicate any blocking is due to network latency (again, not anything to do with the library).

**Comment by dhermes** [comment]
@kir-google-cloud-pubsub Just sent an email as well. Cheers.

**Comment by tseaver** [comment]
If the reported latency is at the point of `Topic.publish`:  note that our GAX API helper maintains API compatibility with the JSON-over-HTTP version, returning the message ID directly to the caller  It therefore disables the GAX "bundling" feature.  We've discussed adding another method (e.g., `Topic.publish_async`) which would be available only under GAX, and which would not return message IDs, but rather the GAX event object.  Users publishing multiple messages simultaneously would gain lower latency (no need to wait for message delivery) in exchange for not being able to track the message IDs at point-of-call (they would need to call `even.wait()` at some point to get them).

**Comment by kir-google-cloud-pubsub** [comment]
Pardon the level of my ignorance here -- don't know what GAX bundling does.  You mean that this is because the Topic.publish() call is blocking?  That still seems odd because the 130ms the user was able to get with gRPC in python indicates that (1) they used a blocking implementation because an async call would not take that long to return; (2) the baseline for full response is still 270ms longer in python.  That seems like a lot for things that don't happen over network.

**Comment by dhermes** [comment]
I did some [benchmarking][1] and it seems like 200ms is the average, when sending a lot of messages, though the number of messages and the duration is only about 65-70% correlated.

It may be more interesting to run this on 50 different machines instead of re-constructing a connection 50 different times, since the OS may be keeping the socket open and making future calls faster.

[1]: https://gist.github.com/dhermes/36ab9af1e4e3f0543f647c0769b06bab

**Comment by kir-titievsky** [comment]
Summarizing some off-line discussion with @dhermes:
- The user shared their python implementation: `from events import pubsub_client
    topic_name = ".".join(['metrics', aid, lid, mid, met])
    topic = pubsub_client.topic(topic_name)

    with topic.batch():
        for timestamp, value in data:
            msg = json.dumps({
                'timestamp': timestamp,
                'value': value
            })
            topic.publish(msg)
`
This code sends every message in a separate request, explaining the large latency.  Proper batch implementation would have been:
` with topic.batch() as batch:
     # redacted code 
     batch.publish(msg)
`

This explains the 400ms latency in the python sample but not the 130ms latency for the gRPC implementation.  Working on that now.

**Comment by dhermes** [comment]
> explaining the large latency...explains the 400ms latency

It doesn't explain latency, but it explains why the block of code might take 400ms. Though if there was a lot of requests (i.e. a lot of entries in the `data` iterator), it'd take a lot more than 400ms.

**Comment by tseaver** [comment]
@kir-titievsky Your update, correcting the batch usage, seems fine to me.  If hand-marshalling the data using `json.dumps` is not a hard requirement, you might consider sending `timestamp` as an [attribute](https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage#FIELDS.attributes), e.g.:

```python
with topic.batch() as batch:
     for timestamp, value in data: 
       batch.publish(value, timestamp=timestamp)
```

which ought to shave off more cycles.

**Comment by lukesneeringer** [comment]
Hello! :-)
First, a _mea culpa_; I have not done as good of a job at keeping up with issues as I should have. If you are getting this (I admit it) cut and paste, it is likely because your issue sat for too long.

In this case, I have been in the process of making a radical update to the PubSub library (#3637) to add significant performance improvements and a new surface, which we hope to launch soon. As such, I am clearing out issues on the old library. It is my sincere goal to do a better job of being on top of issues in the future.

As the preceding paragraph implies, I am closing this issue. If the revamped library does not solve your issue, however, please feel free to reopen.

Thanks!
