### ISSUE TITLE
Needed: Implement system test for orphaned subscriptions

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2328]
See #2080 and #2248

Assigned to Takashi so he can help us get in touch with a service owner that can say "give it up already" or help us keep the test from going flaky.

**Comment by lukesneeringer** [comment]
Hello! :-)
First, a _mea culpa_; I have not done as good of a job at keeping up with issues as I should have. If you are getting this (I admit it) cut and paste, it is likely because your issue sat for too long.

In this case, I have been in the process of making a radical update to the PubSub library (#3637) to add significant performance improvements and a new surface, which we hope to launch soon. As such, I am clearing out issues on the old library. It is my sincere goal to do a better job of being on top of issues in the future.

As the preceding paragraph implies, I am closing this issue. If the revamped library does not solve your issue, however, please feel free to reopen.

Thanks!
