### ISSUE TITLE
pip install google-cloud-storage doesn't work

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/google-cloud-python#2454]
[storage#quick-start](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/storage#quick-start) says you install the client lib by doing `pip install --upgrade google-cloud-storage`, which doesn't work:

```sh
$ pip install --upgrade google-cloud-storage
Collecting google-cloud-storage
  Could not find a version that satisfies the requirement google-cloud-storage (from versions: )
No matching distribution found for google-cloud-storage
```

**Comment by dhermes** [comment]
We have yet to make a release to `google-cloud-storage`, sorry you got caught in the weird transitional state this library is in. I plan on cutting a release some time today.

Follow along in #2441.

Closing this since it is equivalent to #2441 (and the known issue, that release is needed ASAP)

Similar to #2448.

**Comment by jerjou** [comment]
Ah - thanks!

**Comment by dhermes** [comment]
Sure thing. Thanks for filing / caring.

**Comment by dhermes** [comment]
Hooray!

https://pypi.python.org/pypi/google-cloud-storage/0.20.0
