### ISSUE TITLE
Is google-cloud-python compatible with google protobuf?

### ISSUE THREAD

**Issue by wakahiu** [GoogleCloudPlatform/google-cloud-python#2563]
This question if cross-referenced from [here](https://github.com/tensorflow/tensorflow/issues/5056) since it spans both repos/accounts.

--------------------------------------------------------------------------------------------
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
- [Tensoflow Installation from source README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#installing-from-sources)
- [Old google-cloud-sdk question of code.google.com](https://code.google.com/p/google-cloud-sdk/issues/detail?id=538
)

### Environment info
Ubuntu 14.04

### Installed version of CUDA and cuDNN: 
Cuda Toolkit 7.5 and cuDNN v5

### pip packages installed from source, provide 

https://google-cloud-python.readthedocs.io/en/stable/#

```
$ git clone git://github.com/GoogleCloudPlatform/google-cloud-python.git
$ cd google-cloud-python
$ python setup.py install
```

Tensorflow source
1. The commit hash (`git rev-parse HEAD`): 
```
2ed280b4f553e6aa1c7fe0bb41d52456a0ae452c
```
2. The output of `bazel version`
```
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
Trying to import google.cloud
```
python -c "from google.cloud import logging as gclogging;"
```
results in the following error
```
ImportError: No module named cloud
```
### What other attempted solutions have you tried?
Whenever I install google protobuf using either of the following commands
```
sudo pip install /tmp/tensorflow_pkg/tensorflow-0.11.0rc0-py2-none-any.whl
# OR
pip install dist/<wheel file name>
```

I can no longer import google.cloud. 

### Logs or other output that would be helpful
I'm aware of the fact that you can build TensorFlow with Google Cloud Platform support comes with integration when running  ``./configure``. Howoever it's not clear how to integrate with Google Stackdriver.

**Comment by wakahiu** [comment]
Essentially, my question is. It seams that by installing `protobuf` immediately lose the google.cloud modules. Is there a namespace collision such that google can't import two google modules as indicated here?
https://code.google.com/p/google-cloud-sdk/issues/detail?id=24

**Comment by dhermes** [comment]
Short answer: Yes https://pypi.python.org/pypi/google-cloud is compatible with https://pypi.python.org/pypi/protobuf

----

We've seen a decent number of issues like this. It's unfortunate, but there isn't much we can do. It's either due to

- `pip` / `setuptools` mishandling an upgrade of a namespace package
- an older version of https://pypi.python.org/pypi/protobuf installed (older versions don't use)
- you have a different instal (e.g. TensorFlow) which is not properly a namespace package

Note, we [depend on][1] `protobuf` in our `google-cloud-core` package, which **all** the services depend on.

----

I recommend starting with a fresh environment and installing our package from PyPI, not from source:

```
(venv) $ pip install --upgrade google-cloud
```

----

To figure out what may be going wrong with the `google` namespace or the `google.cloud` namespace package, you'll need to import those objects and inspect the `__file__` and/or `__path__` attributes.

----

The namespace collision referenced is from 2014 and has been resolved for more than a year.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/3d28a5ceb1cba844e11710c98eac7933fbb4e977/core/setup.py#L56

**Comment by wakahiu** [comment]
Thanks a lot @dhermes
