### ISSUE TITLE
Documentation URLs

### ISSUE THREAD

**Issue by Fkawala** [GoogleCloudPlatform/google-cloud-python#2566]
Hello, 

I noticed that [1] references [2] as documentation. This documentation describes the `google-cloud` package. I guess that [1] should reference [3] as documentation. I am right ?

[1] https://googlecloudplatform.github.io/google-cloud-python/ 
[2] https://googlecloudplatform.github.io/google-cloud-python/stable/
[3] https://googlecloudplatform.github.io/google-cloud-python/0.18.1/index.html

**Comment by daspecster** [comment]
@Fkawala, thanks for the question!

The way it is now, is actually correct.
The current stable version of `google-cloud-python` is 0.20.0 and that is why [1] references [2].

I'm guessing that you're wondering this because the styling is different? We have a framework that keeps the styling consistent between the different languages but that ended up breaking when we switched to namespace packages. It did a lot of introspection to pull data elements from the code and several areas of that do not work with namespace packages.

I'm going to close this for now since we're tracking this here https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2352. Feel free to reopen if you have other questions!
