### ISSUE TITLE
Can't set table timestamp precision with python API

### ISSUE THREAD

**Issue by destijl** [GoogleCloudPlatform/google-cloud-python#2569]
I didn't realise per-table timestamp precision was a thing because it is missing from the python API, but is present in the RPC API:
https://cloud.google.com/bigtable/docs/reference/admin/rpc/google.bigtable.admin.v2#google.bigtable.admin.v2.Table.TimestampGranularity

It's REALLY not obvious that the table is in ms precision by default, and is silently dropping usec (granularity isn't mentioned at all in docs I've read). This wasn't visible to me until I happened to try and filter by a value that didn't divide evenly into ms and got:

```
Timestamp granularity mismatch. Expected a multiple of 1000 (millisecond granularity), but got 500.
```

This also explains some of my problems in:
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2397

although the InvalidChunk problem might be independent.

**Comment by dhermes** [comment]
@destijl It's absent from the API because milliseconds is the [only allowed value][1]. This is also in the [docs][2] for table.

AFAICT this is unrelated to #2397.

----

Closing this out. LMK if there are issues remaining.

[1]: https://github.com/googleapis/googleapis/blob/37cc0e5acae50ee91f00827a7010c3b07dfa5311/google/bigtable/admin/v2/table.proto#L32-L39
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/392f0f8b2ffaee98766f2851df72221051124100/bigtable/google/cloud/bigtable/table.py#L40

**Comment by destijl** [comment]
Ah. I'd suggest putting it at least here:
https://googlecloudplatform.github.io/google-cloud-python/stable/bigtable-row-filters.html#google.cloud.bigtable.row_filters.TimestampRange

so users don't need to find out via an exception. ms precision is actually a fairly big problem for us, I'm going to send you an email separately.

**Comment by dhermes** [comment]
Indeed, we should probably do something like [this][1] in `TimestampRange.to_pb()`.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/392f0f8b2ffaee98766f2851df72221051124100/system_tests/bigtable.py#L330-L338
