### ISSUE TITLE
Emulator Docs/Functionality are not discoverable.

### ISSUE THREAD

**Issue by Temikus** [GoogleCloudPlatform/google-cloud-python#2593]
One needs to simply:

```
$ gcloud beta emulators pubsub env-init
export PUBSUB_EMULATOR_HOST=localhost:8737

$ export PUBSUB_EMULATOR_HOST=localhost:8737
```

to use the lib with the emulator. However, it is not mentioned anywhere in Docs and confuses some users. I had to go digging into the issues to figure out it's an env variable personally.

Is it possible to add the emulator setup to the docs?

**Comment by kir-titievsky** [comment]
This has now been included in https://cloud.google.com/pubsub/docs/emulator .  
@Temikus How might we make this more discoverable?

**Comment by lukesneeringer** [comment]
Hello! :-)
First, a _mea culpa_; I have not done as good of a job at keeping up with issues as I should have. If you are getting this (I admit it) cut and paste, it is likely because your issue sat for too long.

In this case, I have been in the process of making a radical update to the PubSub library (#3637) to add significant performance improvements and a new surface, which we hope to launch soon. As such, I am clearing out issues on the old library. It is my sincere goal to do a better job of being on top of issues in the future.

As the preceding paragraph implies, I am closing this issue. If the revamped library does not solve your issue, however, please feel free to reopen.

Thanks!
