### ISSUE TITLE
CloudML Integration

### ISSUE THREAD

**Issue by Fematich** [GoogleCloudPlatform/google-cloud-python#2672]
I am working on a `google-cloud-ml` integration at this moment. Since I don't know when I will be able to finish this, I wanted to share this already before doing a PR, so that my efforts are not in vain.

Latest version is availabe [here](https://github.com/Fematich/google-cloud-python/tree/cloudml).

**Comment by daspecster** [comment]
Thanks @Fematich!

This might be some some interest to you https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2660.

**Comment by dhermes** [comment]
Thanks for the heads up. Regarding

> so that my efforts are not in vain.

The best way to do this is to start with a planned usage RST doc, so we can discuss the interface before you write too much code.

A PR with a finished product dumped on the reviewers is a very bad idea. Once the interface is agreed upon, you can send piece-by-piece PRs to get the implementation checked in (the smaller the PRs, the faster the review and the less likely the chances a reviewer misses something due to fatigue).

**Comment by Fematich** [comment]
Thank you both, really useful!
I will start with the usage RST, and come back once I finished a piece.

**Comment by eeveeta** [comment]
@Fematich any news on the RST?

**Comment by lukesneeringer** [comment]
Actually going to close this since it looks like it has languished. @Fematich feel free to open a new issue (preferred over reopening this one) if you want to go down this route.
