### ISSUE TITLE
Remove support for API_KEY in translation

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2734]
See #2731

**Comment by jonparrott** [comment]
@puneith our sample over at python-docs-samples still uses an API Key. Can we switch the sample over to service account credentials?

**Comment by puneith** [comment]
This still uses API_KEY https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/translate/google/cloud/translate/client.py

**Comment by dhermes** [comment]
@puneith The point (I think) was that by moving the sample away from the API key feature, we could more easily remove support for that feature in this library in future versions.

**Comment by puneith** [comment]
Got it. I will make the appropriate changes.

**Comment by geoffwalmsley** [comment]
I have recently started having problems making simple api-key translation calls. It works ok with one virtualenv, but running in a different virtualenv, and/or different project causes this error:

google.cloud.exceptions.Forbidden: 403 Google Translate API has not been used in project google.com:cloudsdktool before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/translate.googleapis.com/overview?project=google.com:cloudsdktool then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. (GET https://translation.googleapis.com/language/translate/v2?target=en&q=mein&source=de)


It looks like it's trying to use the project cloudsdktool rather than the one I have setup using gcloud. Any idea how to fix this? It used to work so easily!!

**Comment by daspecster** [comment]
@geoffwalmsley are you setting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable?

Otherwise you should be able to set the project when creating the `Client(project='my-project')`.

**Comment by jonparrott** [comment]
@geoffwalmsley this is a quirk of how default credentials works. In your case the credentials are being supplied by the Cloud SDK. Unfortunately, these credentials are not sufficient for using the translate API. You'll need to download a service account key and use that.

**Comment by dhermes** [comment]
@jonparrott Are you still opposed to removing support for API key? You were concerned that it was needed for Python clients which can't store secrets, though the API key is itself a secret.

**Comment by jonparrott** [comment]
I'm not opposed to removing it.
