### ISSUE TITLE
CONTRIBUTING doc out-of-date: how to install locally

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/google-cloud-python#2785]
[CONTRIBUTING.rst](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/CONTRIBUTING.rst) is kind of confusing, specifically the part about using tox to create an environment.

Someone had problems using `tox -r --notest -e py27` to "poke around", as far as I can tell `skip_install` is true so the environment is not actually created from the root of the repo. Maybe it meant to do so only from a specific package?

I also think since many tox files don't actually install the `setup.py` deps, it's confusing to suggest using `tox` to install things, probably better just to use `pip`.

**Comment by daspecster** [comment]
@waprin the reason that we're using tox right now because of the namespace package issue for using the `--develop` flag.

See: https://github.com/pypa/setuptools/issues/250

I've tried a couple things but the way that @dhermes has tox setup right now has been the only way to reliably develop without accidentally grabbing a cached version of the library.

Maybe I'm missing your point though?

**Comment by jcoatgoogle** [comment]
Just linking this to https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2786, in which I detail a bit more of my misadventures with tox

For using pip instead, any pointers on what to do? Happy to add it to the docs

**Comment by dhermes** [comment]
@waprin That is just bit-rot in the `CONTRIBUTING` doc. I wrote it before I made those changes to `tox -e py27,py34,py35`.

What'd I'd really like to do is disable them, since the "umbrella" test runs are handled by https://github.com/GoogleCloudPlatform/google-cloud-python/blob/d775489da48d594ce5173a4078af4a0d3d2863f4/scripts/run_unit_tests.py

**Comment by jcoatgoogle** [comment]
Hm, the tox solution started failing again. I tried deleting all the .tox directories, but the issue I'm seeing is that I have a change to datastore/ which depends on a change in core/, but I'm not able to see the change in core/. It's weird because it was working...alas, I rebased in master, but I'm curious if there's a way to properly deal with that? I've checked the site-packages and the change is in fact not reflected in the new file... not sure if something changed, or if I somehow got lucky earlier?!

To unblock myself I can just manually copy the files into site-packages... is this sort of thing meant to be supported?

Thanks again

**Comment by dhermes** [comment]
@jcoatgoogle 

1. Are you running `tox -e py27` in the project root or in the `datastore/` dir?
1. Make sure you have the latest version checked out, it sounds like you're running into a problem that's been solved for a few weeks
1. Ping me on Hangouts?
