### ISSUE TITLE
Vision and Speech snippets?

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2987]
So there are a couple ways that snippets are run right now.

The old way with `{service}-snippets.py` or the way @dhermes has done with [doctest for datastore](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/65213a1ebe4ce18a50b922388f8d36328de08449/system_tests/datastore.py#L526).

Are we for sure going to use doctest and head down that route?

**Comment by dhermes** [comment]
I am :+1: for the approach [set forth in datastore][1] (as @daspecster already linked). Obviously, as the author, this is my preference.

I'm open to @tseaver and @lukesneeringer opinions.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/65213a1ebe4ce18a50b922388f8d36328de08449/system_tests/datastore.py#L526

**Comment by lukesneeringer** [comment]
Glancing at this code very briefly and early in the morning, it looks like it:

  * Compiles docs using Sphinx based on the code.
  * Runs in `:: code..` snippets it finds and complains if any of them error.

Seems reasonable in principle. I would be interested in a way to make that not datastore-specific (but in the meantime...)

**Comment by dhermes** [comment]
@lukesneeringer Putting it in `system_tests/datastore.py` was intentional: we want to make sure the snippets aren't "right with mock, wrong with actual code". So the only datastore specific pieces in that class are fairly easy to factor out (just used for listing all modules in the datastore package and for creating a temporary directory with a simple Sphinx conf containing only datastore modules)

**Comment by lukesneeringer** [comment]
Okay. Seems fine to me.

**Comment by daspecster** [comment]
OK SGTM. Onward and forward!

**Comment by daspecster** [comment]
@tseaver I just realized you hadn't weighed in. Feel free to reopen if you have some feedback!
