### ISSUE TITLE
Add more useful header info on HTTP requests

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3006]
Most relevant place: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/9619004959def22ad2084691f382dc1cada46afd/core/google/cloud/_http.py#L177

May want to make this easier to use upstream

/cc @lukesneeringer

**Comment by tseaver** [comment]
Seems like we could override the `USER_AGENT` class attribute for the APIs which use `JSONConnection`, and derive it from `pkg_resources` (maybe add a helper for that?).  E.g.:

```python
from pkg_resources import get_distribution

from google.cloud._http import JSONConnection


class Connection(JSONConnection):
    USER_AGENT = 'google-cloud-foo-python/{0}'.format(
        get_distribution('google-cloud-foo').version)
```

I don't know whether the `-python` suffix should be there.  @lukesneeringer can you confirm?

**Comment by lukesneeringer** [comment]
It is actually moving to a new header, `X-Goog-API-Client`, and the client library is going to be abbreviated `gccl` (**g**oogle **c**loud **c**lient **l**ibrary).

We also intend to track the language via `gl-python/{v}`, which should appear at the beginning of the string.

We probably still need to set a User-Agent string (just because it is considered good practice), and it does not matter what it is. `google-cloud-core/{v}` seems appropriate for that but I will defer to whatever you folks want (provided it is sane).

**Comment by dhermes** [comment]
@lukesneeringer The value of `gcloud-python` used to be deemed "sacred" to preserve some reporting internal to Google. That may no longer be true.

**Comment by lukesneeringer** [comment]
This is no longer true. The new header is superceding the old one.

**Comment by dhermes** [comment]
#3035 is most of the "intellectual way" towards this

**Comment by dhermes** [comment]
Remaining APIs:

- [ ] `bigquery`
- [ ] `datastore`
- [ ] `dns`
- [ ] `error_reporting`
- [ ] `language`
- [ ] `logging`
- [ ] `monitoring`
- [ ] `pubsub`
- [ ] `resource_manager`
- [ ] `runtimeconfig`
- [ ] `speech`
- [ ] `storage`
- [ ] `translate`
- [ ] `vision`
