### ISSUE TITLE
Integrate Spanner DB-API with Django

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#3024]
Blocked on #3022.  Can run in parallel with #3023.

See: https://docs.djangoproject.com/en/1.10/ref/databases/

**Comment by lukesneeringer** [comment]
In an effort to get my project management to be a bit more sane, I am going to try something else in lieu of single issues that represent large projects.

I have referenced this on a [wiki page devoted to our significant feature backlog][1]. Discussion of this particular feature is still welcome here, although I am going to close this issue until such time as this is something we take on.

  [1]: https://github.com/GoogleCloudPlatform/google-cloud-python/wiki/Feature-Backlog

**Comment by AndreCimander** [comment]
Looking forward to this, I'm currently forced to re-invent the wheel by writing a thin "django-inspired" model/queryset wrapper around the cloud spanner library in order to enable our junior/mid-level developers to productively work with spanner...

Not having a local developer spanner instance and having no orm support are two **major** issues – we are already considering to switch to CockroachDB instead.
