### ISSUE TITLE
Exception Handling Design

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#3040]
Created from https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2936.

@dhermes I wasn't 100% sure if you had this all planned out or not, but if there are pieces to it or design questions we could talk about it here instead of in PRs.

The idea(to the best of my knowledge) is to better handle exceptions between our services that handle multiple transports. There is also a differentiation between exceptions that are raised from the upstream service and just normal transport exceptions.

We should have a clear distinction between service related exceptions and transport related exceptions and manage those consistently across all services.

**Comment by dhermes** [comment]
Sure. The only TODO I am aware of is:

- (At a high-level): Support [RPC status codes][1] for the transport exceptions we raise (this should be fine, since the HTTP errors usually/always? contain the RPC status code)

[1]: https://github.com/googleapis/googleapis/blob/cc80e9432f082553cb7e5af0b29cb8a89d9ffb46/google/rpc/code.proto#L33

**Comment by tseaver** [comment]
#3444 is the first step towards this:  it makes the RPC status code -> exception type mapping available everywhere, hoisting the '_catch_remap_gax_error()` helper from `bigtable.exceptions` to `core.exceptions`.

**Comment by lukesneeringer** [comment]
Superceded by #3738.
