### ISSUE TITLE
speech_contexts parameter of Sample.long_running_recognize() limited to 50 phrases?

### ISSUE THREAD

**Issue by kosmiciatakuja** [GoogleCloudPlatform/google-cloud-python#3330]
The `speech_contexts` parameter to `long_running_recognize` method of the Sample has a description that starts with: 

> A list of strings (max 50)...

Meanwhile, the true API limits for this parameter are described here: https://cloud.google.com/speech/limits#content
and specifically say:

> Phrases per request 	**500**
> Total characters per request 	10,000
> Characters per phrase 	100

Does the python client API impose additional limits (50 strings) then? Or is it just an error in the description of this parameter and we can use 500 strings with total 10000 characters and 100 characters per string? 

----

1. OS type and version
Linux 4.10.11
2. Python version and virtual environment information `python --version`
3.6.0
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
Version: 0.24.0
4. Stacktrace if available
n/a
5. Steps to reproduce
n/a
6. Code example
n/a

**Comment by dhermes** [comment]
@lukesneeringer Do you know the answer to this? Could you point an API owner to this question?

**Comment by lukesneeringer** [comment]
Since this ticket was filed, we have released a new Speech library which entails effectively a complete rewrite. Since it is very likely to solve this issue, I am closing this. However, please feel free to reopen if my closure is premature.

Note: Make sure you are using `google.cloud.speech.SpeechClient`, as the old `Client` still exists as a deprecated artifact for a little longer.
