### ISSUE TITLE
IAM policy should return an empty set of the bindings do not exist

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#3346]
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/bd9fdfba07fac63a91847628613928a569250c0f/core/google/cloud/iam.py#L71

Should return an empty set if no bindings are set for that role.

**Comment by dhermes** [comment]
Current behavior leads to `KeyError`, yes?

**Comment by jonparrott** [comment]
ya, I'd like to be able to do:

```python
policy = something.get_iam_policy()
policy['roles/editor'].add('whatever')
something.set_iam_policy(policy)
```

and it'll work regardless of if any editors had been previously set.

**Comment by dhermes** [comment]
@jonparrott ISTM like you want a `collections.defaultdict(set)`?

In #3325 a similar snippet was **failing** because `policy.owners` returned a `frozenset`. In the `__getitem__` case, the raw binding will be returned, which we [guarantee][1] is a `set`. Is it a bad thing that the two different means of access produce different behavior?

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/bd9fdfba07fac63a91847628613928a569250c0f/core/google/cloud/iam.py#L73-L74

**Comment by jonparrott** [comment]
Defaultdict is pretty much what I'm after, in terms of behavior.
I'm fine with the old/deprecated methods returning a frozenset.
