### ISSUE TITLE
pubsub: allow setting a pull HTTP timeout

### ISSUE THREAD

**Issue by yarharel** [GoogleCloudPlatform/google-cloud-python#3367]
What I would like to do is be able to send a timeout param in the pull request to tell pubsub to send back a response after a 30000ms (or something else) if no messages are published during that time.

Exactly the same issue as in Node:
https://github.com/GoogleCloudPlatform/google-cloud-node/pull/981

**Comment by tseaver** [comment]
This would involve adding a `timeout` option to the `_gax._SubscriberAPI.subscription_pull` method (similar to the one added to `_gax._PublisherAPI.topic_publish` method in deca383a), and surfacing that option at the `subscription.Subscripton` level (`Topic.publish` needs to expose the `timeout` too).

**Comment by lukesneeringer** [comment]
Hello! :-)
First, a _mea culpa_; I have not done as good of a job at keeping up with issues as I should have. If you are getting this (I admit it) cut and paste, it is likely because your issue sat for too long.

In this case, I have been in the process of making a radical update to the PubSub library (#3637) to add significant performance improvements and a new surface, which we hope to launch soon. As such, I am clearing out issues on the old library. It is my sincere goal to do a better job of being on top of issues in the future.

As the preceding paragraph implies, I am closing this issue. If the revamped library does not solve your issue, however, please feel free to reopen.

Thanks!
