### ISSUE TITLE
test_async_recognize_local_file() is flaky

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3392]
See: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1781

[Failed line][1] assumes `operation.results` will be a list, but instead it is `None`.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/391c6fd807f5f4c0ea7066ec086cfa67b47a637e/speech/tests/system.py#L188

**Comment by lukesneeringer** [comment]
Since this ticket was filed, we have released a new Speech library which entails effectively a complete rewrite. Since it is very likely to solve this issue, I am closing this. However, please feel free to reopen if my closure is premature.

Note: Make sure you are using `google.cloud.speech.SpeechClient`, as the old `Client` still exists as a deprecated artifact for a little longer.
