### ISSUE TITLE
Upload file to GCS with Storage Object Creator role.

### ISSUE THREAD

**Issue by tweeter0830** [GoogleCloudPlatform/google-cloud-python#3433]
Is there a way to upload a file to GCS using the python api using a service account with write only privileges?

I'm using the following code to do try this right now:
```python
    client = storage.Client.from_service_account_json(
        service_account_filepath,
        project=key_file_dict['project_id'],
    )
    bucket = self.client.get_bucket(gcs_bucket_name)
    blob = bucket.blob(gcs_filepath)
    blob.upload_from_filename(filepath)
```

This fails at the following line:
```python
    bucket = self.client.get_bucket(gcs_bucket_name)
```

I get the following error:

```python
...
google/cloud/storage/client.py", line 173, in get_bucket
    bucket.reload(client=self)
...
google.cloud.exceptions.Forbidden: 403 Caller does not have storage.buckets.get access to bucket aircraft-audio-data.
```

This is kind of expected as my service account has the "Storage Object Creator" role and nothing else.

**Comment by dhermes** [comment]
@tweeter0830 Use [`client.bucket`][2] instead of [`client.get_bucket`][1]. This will simply create a local `Bucket` object without trying to call `storage.buckets.get` via the API.

[1]: https://googlecloudplatform.github.io/google-cloud-python/stable/storage-client.html#google.cloud.storage.client.Client.get_bucket
[2]: https://googlecloudplatform.github.io/google-cloud-python/stable/storage-client.html#google.cloud.storage.client.Client.bucket

**Comment by tweeter0830** [comment]
Thanks!

**Comment by dhermes** [comment]
Sure thing. Let us know if there is some other problem I hadn't considered, we're happy to help more.

**Comment by SaraDupont** [comment]
Super useful !! Could be a good information to include in the API's documentation !
