### ISSUE TITLE
How to serialize to json or dict that response from vision api?

### ISSUE THREAD

**Issue by inska** [GoogleCloudPlatform/google-cloud-python#3485]
Hi, 

Google Cloud SDK works well to get annotation responses via vision API, and I just like to know how can I serialize the response. Is there any helper or serializer for Google response objects? Otherwise, should I parse and build dictionaries from the response object by manual?

Sincerely,
Inska

# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

- https://github.com/GoogleCloudPlatform/google-cloud-python/issues
- http://stackoverflow.com/questions/tagged/google-cloud-python

If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1. OS type and version
OS X El Capitan
2. Python version and virtual environment information `python --version`
2.7.13
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
157.0.0
4. Stacktrace if available
5. Steps to reproduce
6. Code example

**Comment by dhermes** [comment]
@inska Can you provide a code snippet that produces the thing you'd like to serialize?

**Comment by lukesneeringer** [comment]
@inska Sadly, the objects in the current Vision library lack serialization functions (although this is a good idea).

It is worth noting that we are about to release a substantially different library for Vision (it is on master of this repo now, although not released to PyPI yet) where this will be possible. Note that it is a backwards-incompatible upgrade, so there will be some (hopefully not too much) conversion effort.

That library returns plain protobuf objects, which can be serialized to JSON using:

```python
from google.protobuf.json_format import MessageToJson
serialized = MessageToJson(original)
```

You can also go to dictionaries using something like [protobuf3-to-dict][1].

P. S. I am going to go ahead and close this issue, since I hope I have answered it, but please feel free to reopen if needed!

  [1]: https://pypi.python.org/pypi/protobuf3-to-dict/

**Comment by arycloud** [comment]
Hi @lukesneeringer , I have tried it but it return an error like: `AttributeError:'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'DESCRIPTOR'`
How can I resolve this error?

**Comment by u2takey** [comment]
@lukesneeringer same problem with @arycloud `AttributeError:'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'DESCRIPTOR'`

**Comment by rootVIII** [comment]
Thanks @lukesneeringer 

I can't believe how many google searches it took me to find the answer you posted.

**Comment by zyfang** [comment]
@arycloud @u2takey I had the same problem as you and I realized it's because I "unpack" the response before trying to convert it to json or dict. For example:
`response = client.annotate_image({'image': {'source': {'image_uri': image_url}}, 'features': features, })`
My program did the equivalent of:
`MessageToJson(response.label_annotation)`  , which results in `AttributeError:'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'DESCRIPTOR'`

Now I do:
`response = MessageToDict(response, , preserving_proto_field_name = True)
desired_res = response["label_annotation"]
`

**Comment by cybercser** [comment]
Thanks @lukesneeringer

**Comment by digglife** [comment]
Cool. Thank you @lukesneeringer !

**Comment by henrihe1** [comment]
> Thanks @lukesneeringer
> 
> I can't believe how many google searches it took me to find the answer you posted.

Thanks a lot @lukesneeringer !
@rootVIII: I can sooo relate.

**Comment by piratezoro** [comment]
Hi @lukesneeringer  I was actually using ImageAnnotatorClient with dask for parallel computation.
Until now I was just making new ImageAnnotatorClient for each image which is cause memory overflow issue. So I was planning on creating a single instance of ImageAnnotatorClient object and getting all the work done.But with dask client.map method I am unable to serialize the ImageAnnotatorClient object.So is there a way I can serialize it and the deserialize it. I tried the above method but it does not work.

**Comment by akshat-khare** [comment]
It is not working again. I am still facing this Descriptor error.
