### ISSUE TITLE
Speech client incorrectly computes chunk sizes

### ISSUE THREAD

**Issue by wolfmanstout** [GoogleCloudPlatform/google-cloud-python#3565]
This code reads chunk_size bytes from the audio file instead of reading chunk_size * encoding_frame_size bytes:
[https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech/_gax.py#L348][1]

This seems like  a bug, since the documentation for chunk_size  implies that it is trying to achieve 100 ms chunks:
[https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech/sample.py#L78][2]

In a typical LINEAR16 encoding, this means that we would actually be reading 50 ms chunks instead of 100.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/39feb3e23d451963ca31b383d8b395afcf7ab817/speech/google/cloud/speech/_gax.py#L348
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/39feb3e23d451963ca31b383d8b395afcf7ab817/speech/google/cloud/speech/sample.py#L78

**Comment by lukesneeringer** [comment]
Summoning @geigerj. Any idea if this is something we can easily change?

**Comment by geigerj** [comment]
@lukesneeringer Seems like you can figure out the encoding_frame_size from `sample.encoding` and just do the calculation @wolfmanstout suggested?

**Comment by lukesneeringer** [comment]
Since this ticket was filed, we have released a new Speech library which entails effectively a complete rewrite. Since it is very likely to solve this issue, I am closing this. However, please feel free to reopen if my closure is premature.

Note: Make sure you are using `google.cloud.speech.SpeechClient`, as the old `Client` still exists as a deprecated artifact for a little longer.
