### ISSUE TITLE
Update Documentation Link on Pypi Page

### ISSUE THREAD

**Issue by johnjameswhitman** [GoogleCloudPlatform/google-cloud-python#3653]
The Pypi package page for [google-cloud-language v0.25.0](https://pypi.org/project/google-cloud-language/0.25.0/) links to the wrong Documentation site (might just be out of step with head).
- Is: https://googlecloudplatform.github.io/google-cloud-python/stable/language-usage.html
- Should be: https://googlecloudplatform.github.io/google-cloud-python/stable/language/usage.html

I couldn't find where this is versioned, otherwise would have submitted a PR.

**Comment by dhermes** [comment]
Thanks for filing @johnjameswhitman! I fixed this "broken link" issue in #3631. Unfortunately, AFAIK there is current (https://github.com/pypa/packaging-problems/issues/97) no way to edit package metadata (which includes the README), so that version is "stuck" with a bad link.

The **real** fix going forward is to have fully versioned docs (tough right now with our UBER-package) and to link in the README on PyPI to the versioned docs.

**Comment by lukesneeringer** [comment]
I am going to go ahead and close this. I agree with the description of the problem, and the fix, but tracking this as a separate line item probably is not going to be all that useful.

@johnjameswhitman Thank you for reporting, and we have a medium-term plan that will sort this out, even for old versions.
