### ISSUE TITLE
Expose read-isolation parameters in 'Database.read'/'Database.execute_sql'

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#3659]
~~And therefore in `Snapshot.read` / `Snapshot.execute_sql`.~~

And therefore in `Session.read` / `Session.execute_sql`

From https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3615#issuecomment-317510958

**Comment by vkedia** [comment]
I dont think `Snapshot.read` and `Snapshot.execute_sql` should take in isolation parameters since all reads/queries within a multi use snapshot should use the same isolation. So it will be confusing if users can specify those as a parameters for read/query. 
`Database.read` and `Database.execute_sql` shouls take in these parameters and pass those to the constructor of snapshot.

**Comment by tseaver** [comment]
Oops, I mean to say `Session.read` and `Session.execute_sql` (because those are the ones called by `Database.read` / `Database.execute_sql`.

**Comment by vkedia** [comment]
Any updates on this?

**Comment by tseaver** [comment]
#3787 is removing those methods (because #3769).
