### ISSUE TITLE
pylint and Visual Studio Code autocomplete does not see "google/cloud/*" modules

### ISSUE THREAD

**Issue by amsokol** [GoogleCloudPlatform/google-cloud-python#3686]
Dear All,

1. Windows 10

1. Python 2.7.13

1. `pip show google-cloud` output:
Name: google-cloud
Version: 0.26.1
Summary: API Client library for Google Clou
Home-page: https://github.com/GoogleCloudPl
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@googl
License: Apache 2.0
Location: c:\bin\python27\lib\site-packages

pylint and Visual Studio Code autocomplete does not see `google/cloud/*` modules.
The reason is both of them don't understand that `<python>\Lib\site-packages\google\cloud` is path to modules.
The fix is simple: create empty `__init__.py` files inside `<python>\Lib\site-packages\google` and `<python>\Lib\site-packages\google\cloud` folders during installation by `pip`.

Thanks

**Comment by dhermes** [comment]
@amsokol Unfortunately this is an issue with Visual Studio and not with these packages.

The `google` and `google.cloud` packages are namespace packages, so they get imported in a special way by Python. They do have `__init__.py` modules but those are typically untouched because `pth` files get added when these namespace packages get installed.

See: https://packaging.python.org/guides/packaging-namespace-packages/

**Comment by dhermes** [comment]
@amsokol I closed the issue pre-emptively because I don't think there's anything more we could be doing. I'm happy to continue discussing though, I just didn't want the issue to languish.
