### ISSUE TITLE
batch.delete...

### ISSUE THREAD

**Issue by isaachq** [GoogleCloudPlatform/google-cloud-python#3773]
Dont! Work batch.delete+

  File "quickstart.py", line 37, in <module>
    batch.delete('tb_articulo',keyset['bharney@example.com', 'nonesuch@example.com'])
NameError: name 'keyset' is not defined

What is this ???

And  this
   keyset = ['2017-08-01', '2017-08-01']
    batch.delete('tb_articulo',keyset)

    key_set=keyset.to_pb(),
AttributeError: 'list' object has no attribute 'to_pb'

???????

**Comment by lukesneeringer** [comment]
Hi @isaachq,
Thanks for reporting.

Is `quickstart.py` a sample that we provided? If so, it is possible we need to fix it.

`NameError` and `AttributeError` are reasonably standard Python errors. The first is because you had not defined `keyset` yet, and the second because you sent a list where a protobuf message was expected.

If this is code we provided, we definitely want to fix that. :-) If this is code you wrote, then we will need more context in order to provide help. I would also recommend doing some research on exceptions in Python generally.

As this is pretty certainly not an issue in this actual repo, I am going to close this issue for now, but feel free to reopen if appropriate.

**Comment by isaachq** [comment]
The code is from this site 
https://googlecloudplatform.github.io/google-cloud-python/stable/spanner/batch-usage.html
in the section 
Delete records using a Batch

Everything works except delete :(

**Comment by tseaver** [comment]
The example is missing an equals sign:  it should read:

```python
batch.delete('citizens',
    keyset=['bharney@example.com', 'nonesuch@example.com'])
```

**Comment by isaachq** [comment]
Dont Work.... :/
  File ".\quickstart.py", line 29, in <module>
    batch.delete('prueba', keyset=[1,2])
  File "C:\Users\isaac.hernandez\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\spanner\batch.py", line 119, in delete
    key_set=keyset.to_pb(),
AttributeError: 'list' object has no attribute 'to_pb'

**Comment by isaachq** [comment]
Or
  File ".\quickstart.py", line 29, in <module>
    batch.delete('prueba', keyset=[1,2])
  File "C:\Users\isaac.hernandez\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\spanner\batch.py", line 119, in delete
    key_set=keyset.to_pb(),
AttributeError: 'list' object has no attribute 'to_pb'

:(

**Comment by tseaver** [comment]
@isaachq See #3788.

**Comment by isaachq** [comment]
@tseaver  Great!!!!! Awesome!! Thanks

from google.cloud.spanner.keyset import KeySet

to_delete = KeySet(keys=[('1'),('2')])

with database.batch() as batch:
    batch.delete('prueba', to_delete)
