### ISSUE TITLE
Docs lack guidance about choosing job_name parameter

### ISSUE THREAD

**Issue by inglesp** [GoogleCloudPlatform/google-cloud-python#3826]
Many methods on `google.cloud.bigquery.client.Client` take a `job_name` as their parameter but there's no guidance [in the docs](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/client.html) about what the `job_name` should be.

Investigation suggests it needs to be unique, and this is confirmed under the "Generating a job ID" section of [this page](https://cloud.google.com/bigquery/docs/managing-jobs) (which I found through Googling).  That page also suggests using eg Python's `uuid.uuid4()`.

Could some advice about choosing `job_name` be added to https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/client.html?

And better, although it'd be a backwards-incompatible change, could `job_name` be an optional parameter that's generated automatically by BQ?

**Comment by lukesneeringer** [comment]
Hi @inglesp,
So, having BigQuery itself generate a `job_name` is actually a little bit of an anti-pattern, because that has an undesirable effect on retries. So, we want the client library to do it. However, we do have a plan to make it such that _you_ to not have to specify the `job_name`, and the client library will do it for you (using `uuid.uuid4()`), which mitigates this.

**Comment by lukesneeringer** [comment]
Hmm, I thought we had an issue open for this, but I do not see one (I might have closed it by accident last week), so leaving this one open. :-)

**Comment by tswast** [comment]
Duplicate of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3209.

**Comment by lukesneeringer** [comment]
Okay, we did have one. Thanks.
