### ISSUE TITLE
httplib2 -> Request migration problem

### ISSUE THREAD

**Issue by sebastienmorand** [GoogleCloudPlatform/google-cloud-python#3853]
Hi,

The last update migrating httplib2 to Request make google-cloud-bigquery library incompatible with GAE standard, and it was before.

google-cloud-bigquery==0.25.0 => Ok in GAE standard
google-cloud-bigquery==0.26.0 => Ko in GAE standard (request dependency)

**Comment by lukesneeringer** [comment]
Hi @sebastienmorand,
Which dependency of `requests` refuses to install on GAE Standard?

/cc @jonparrott

**Comment by jonparrott** [comment]
The short answer is that due to limitations in the App Engine standard environment, this library is not supported there.

The long answer(s) are over at [#1893](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1893#issuecomment-322512490).

If a previous version of BigQuery worked for you then I would recommend pinning to that version.
