### ISSUE TITLE
Is there any way to specify a client-wide timeout?

### ISSUE THREAD

**Issue by tweeter0830** [GoogleCloudPlatform/google-cloud-python#3861]
I'm using the pubsub client to interact with a pubsub topic via pull/publish on a local machine.

However, sometimes this machine loses connection to the internet.

I would love to set a timeout for all of my pull/publish calls, but I see no reasonable way of doing this.

This points to a larger issue of how you deal with timeouts and lost connection issues in general.

Is there any way to set a (PubSub)  client-wide timeout?

**Comment by tweeter0830** [comment]
To comment a little more about the impact of this:

Not being about to set timeouts for things like pull, subscribe, subscription.close makes this library a no-go for any environment with a flaky internet connection. I don't see any apparent reasonable workaround.

**Comment by lukesneeringer** [comment]
Hi @tweeter0830,
We just released a new Pub/Sub library with a substantially different surface which does, in fact, let you configure this globally for the full client. This library is a full rewrite, though, so there will be some learning curve for you.

We also did not document in detail how to set this, because it is so rare. Essentially, you want to send the `client_config` keyword argument to the `PublisherClient` or `SubscriberClient` constructor. It takes a huge dictionary with, among other things, the timeout information. The defaults for `PublisherClient` are [here][1] and the defaults for `SubscriberClient` are [here][2]. I _think_ it does a deep merge, so you only need to set what you want to override, but I am not 100% certain.

  [1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/pubsub/google/cloud/gapic/pubsub/v1/publisher_client_config.json
  [2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/pubsub/google/cloud/gapic/pubsub/v1/subscriber_client_config.json

**Comment by tweeter0830** [comment]
Thanks for the response. I've gone down this route and subscribe works the way I would like. However, with the following code, I end up with this uncatchable exception during a timeout. In the code below, "caught" will never get printed. Instead, publish blocks forever and I get the stack trace below.

```
    self._publisher = pubsub.PublisherClient(
        client_config=CONFIG,
        credentials=self._credentials)
    self._topic_name = 'projects/{project_id}/topics/{topic}'.format(
        project_id=self._project_id,
        topic=self._topic_id,
    )
    try:
      self._publisher.publish(
         self._topic_name, incident_proto.SerializeToString()).result()
    except Exception:
       print('caught')
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "//local/lib/python2.7/site-packages/google/cloud/pubsub_v1/publisher/batch/thread.py", line 212, in monitor
    return self._commit()
  File "//local/lib/python2.7/site-packages/google/cloud/pubsub_v1/publisher/batch/thread.py", line 173, in _commit
    self.messages,
  File "//local/lib/python2.7/site-packages/google/cloud/gapic/pubsub/v1/publisher_client.py", line 314, in publish
    return self._publish(request, options)
  File "//lib/python2.7/site-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File "//lib/python2.7/site-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File "//lib/python2.7/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "//lib/python2.7/site-packages/google/gax/retry.py", line 143, in inner
    raise exc
RetryError: RetryError(Retry total timeout exceeded with exception, caused by <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>)
```

**Comment by lukesneeringer** [comment]
The reason why the exception is not being caught is because it occurs in another thread, and unfortunately it is _really_ hard to handle exceptions raised in threads. However, note that `publish` returns a future, and `future.result()` will raise the exception in the main thread, where it can be caught.

**Comment by jooon** [comment]
I see the same problem and I think it is the same issue as #4019. I currently get around it, by subclassing thread.Batch and overriding _commit and wrapping the entire call in a try catch that does future.set_exception. It doesn't feel right though, because it will cause all futures to fail in the batch.

**Comment by samx816** [comment]
Is this config only available for google.cloud.pubsub_v1.SubscriberClient and PublisherClient? I want to write a program that utilizes the pull method with a lower timeout limit, but overriding timeout with CallOptions doesn't seem to work. Here is an example snippet:

`from google.cloud.gapic.pubsub.v1 import subscriber_client
from google.gax import CallOptions
import os

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = file_location # modify here
subscription = sub # modify here

client = subscriber_client.SubscriberClient()
options = CallOptions(timeout=2)

while True:
    print("LOOP")
    messages = client.pull(subscription, max_messages=1000, options=options)
    for message in messages.received_messages:
        print(message.message.data)
`

**Comment by danoscarmike** [comment]
@dhermes @lukesneeringer can you please re-evaluate this one?

**Comment by jonparrott** [comment]
@samx816 that definitely seems like an older version, with the newer version you can just specify `timeout=2` when invoking any RPC method.

I'm closing this for now, but if there's something else that needs to be done here we can re-open.
