### ISSUE TITLE
[runtimeconfig] Should be "client.config(...)" not "client.get_config(...)

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/google-cloud-python#3894]
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/bee32c0ae68b1e6cf224f9017c758a8e31e8be83/runtimeconfig/google/cloud/runtimeconfig/config.py#L189

**Comment by tseaver** [comment]
Thanks, the [client class](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/bee32c0ae68b1e6cf224f9017c758a8e31e8be83/runtimeconfig/google/cloud/runtimeconfig/client.py#L56) does indeed have a `config` method (rather than `get_config`).

In addition, that example has a typo, `get_varialbe`.
