### ISSUE TITLE
RTD build broken because of "bad" dependencies in umbrella package

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4001]
https://readthedocs.org/projects/google-cloud-python/builds/5997521/

**Comment by mattrobenolt** [comment]
Same here https://travis-ci.org/getsentry/sentry/jobs/277442282

In our case, this is related to `google-cloud-pubsub` having a looser pin than `google-gox` which was introduced here: https://github.com/googleapis/gax-python/commit/7c018cf3b487a19d1c2ccf59610db15a72407e2a

So when installing just `pip install google-cloud-pubsub` in a new virtualenv, you still end up installing `grpcio==1.6.0` since the parent allows it, but the subdependency then chokes. The change in gax-python also needs to be applied here and a new version tagged so they are in sync.

In the meantime, pinning grpcio in your project should work around it as `grpcio==1.4.0`

**Comment by dhermes** [comment]
@mattrobenolt Your issue is not what I'm referring to here. RTD == Read The Docs and the umbrella issue I'm referring to is just a version bound conflict for `videointelligence`.

Thanks for reporting though.

**Comment by mattrobenolt** [comment]
But it's the same root cause:

> Installed /home/docs/checkouts/readthedocs.org/user_builds/google-cloud-python/envs/latest/lib/python3.5/site-packages/google_cloud_language-0.28.0-py3.5.egg
error: grpcio 1.6.0 is installed but grpcio<1.6dev,>=1.0.2 is required by {'google-gax'}

Just replace `google-cloud-pubsub` with `google-cloud-language`. They are both a problem because the each are more liberal with their dependencies than `google-gox`.

And both of these libraries are within the same repository here.

**Comment by dhermes** [comment]
Ahh I see that now. Cheers!

**Comment by noamt** [comment]
We're really suffering from this issue as well when trying to use `google-cloud-pubsub`.
We use `setuptools` to resolve dependencies and it fails fast on `grpcio 1.6.0 is installed but...`, breaking all our builds. 
Is there a workaround for this?

**Comment by mattrobenolt** [comment]
Just pin grpcio like https://github.com/getsentry/sentry/commit/8fd26a305a6844b9a6425038c65728e43916c100

**Comment by noamt** [comment]
Cheers @mattrobenolt

**Comment by tseaver** [comment]
Thanks for the report!  Current builds are passing, but please feel free to reopen if they break again.

**Comment by dhermes** [comment]
@tseaver They are **not** passing. I manually "wipe" our build cache for about 1/3 of our builds. There is some strange issue where `pip` installs an egg rather than a wheel for some packages listed in `requirements.txt`.

**Comment by chemelnucfin** [comment]
looks like an old issue since it references gax.  Closing.  Reopen or file a new issue if necessary.

**Comment by tseaver** [comment]
The (`latest` build](https://readthedocs.org/projects/google-cloud/builds/) is currently passing, but has only been doing so for the past week.

**Comment by jonparrott** [comment]
I did some tweaks to it in the last few weeks.
