### ISSUE TITLE
PubSub: block while reading topic

### ISSUE THREAD

**Issue by fcaldas** [GoogleCloudPlatform/google-cloud-python#4072]
Hi, 

I have a considerable amount of code depending on `google.cloud.pubsub.Client` and I noticed that on the last versions this object was separated into two objects, one of them being `SubscriberClient` and this new object has a non-blocking behaviour which is causing me some problems.
Since in my use-case I have a cron job that runs once a day and consumes the PubSub I need a way to know when the topic is empty (another process feeds the topic once a day) and stop the job once that happens, the behaviour we had in version 0.27.0 (blocking read) was much friendlier and if I ever needed to do something else while wait I could do that with python `multiprocessing`.

Is there any way of replicating this behaviour with the new 0.28 version of the library?

Thanks

**Comment by lukesneeringer** [comment]
Hi @fcaldas,
Thanks for reporting / asking. :-)

At this time, the Pub/Sub library does not have a blocking call (essentially due to too many people with high performance needs painting themselves into difficult situations).

For your particular use case, I think what I would recommend is relying on the Pub/Sub client's internal management to know when you have burned down everything in your queue. The subscription object (it is actually called a `Policy` internally -- basically the thing with the `.open` method) has a property called `managed_ack_ids`. It will be a set of strings, and each string corresponds to a message that you have pulled in but not acked yet.

If I understand your use case correctly, and you are getting a big burst of messages when you connect and just need to know when those messages are all dealt with, then as soon as `len(subscription.managed_ack_ids)` is zero, you can safely close the subscription.

Basic code (working from the top of my head here) should look something like this:

```python
def callback(message):
    pass  # Your callback implementation.

# Open the subscription.
subscription = subscriber_client.subscribe('/projects/{p}/subscriptions/{s}')
subscription.open(callback)

# Give the subscription time to connect and get initial messages so
# we do not exit early.
time.sleep(5)

# Block until the subscription is empty.
while len(subscription.managed_ack_ids) > 0:
    time.sleep(60)
sys.exit(0)
```

If you need anything else, feel free to ask. :-)
