### ISSUE TITLE
Spanner: IndexError: pop from empty list when merge_array

### ISSUE THREAD

**Issue by yixizhang** [GoogleCloudPlatform/google-cloud-python#4164]
```
return merger(lhs, rhs, type_)
  File ".../google/cloud/spanner_v1/streamed.py", line 259, in _merge_array
    first = rhs.pop(0)
IndexError: pop from empty list
```

**Comment by tseaver** [comment]
@yixizhang Thanks for the report!

@vkedia How is it happening that the back-end is returning an empty partial response chunk?

**Comment by vkedia** [comment]
It can happen if we decide to chunk at the boundary of an array (either top level or nested). In that case we would not mistakenly want to merge with the next Value (in case that too is an array), so we send an empty array as the first value of the next partial result set. For eg say a Row has two columns both of which are of type `ARRAY<INTEGER>`. The values in the first row for these 2 columns are
`[1], [2]`. If we decide to chunk after `[1]`, we need to send an empty list as the first Value in next chunk otherwise you would end merging `[1]` and `[2]` to get a single value `[1, 2]` which is incorrect.

**Comment by tseaver** [comment]
@vkedia OK, seems like we should have an example like that in the JSON-based acceptance tests.

**Comment by vkedia** [comment]
Yeah I agree. I will add this.

**Comment by vkedia** [comment]
Can this be closed?

**Comment by tseaver** [comment]
@vkedia PR #4170 will close it when merged.
