### ISSUE TITLE
Push / append to list in Datastore

### ISSUE THREAD

**Issue by jmgirven** [GoogleCloudPlatform/google-cloud-python#4328]
I have a Datastore entity that represents a video that I am hosting. When this video is uploaded, a group of workers process different versions of the video, and when complete, append the processed version ID to a list in my entity. Something like:

```python
# Get the entity
ds = datastore.Client()
query = ds.query(kind=VIDEO)
query.add_filter('video_id', '=', video_id)
entity = list(query.fetch(limit=1))[0]

# Add the processed version
entity['processed'].append(version_id)

# Save the entity
ds.put(entity)
```

Largely this is OK, but occasionally after all the processing is complete, the entity does not contain all the completed version IDs. I am wondering if this is because two processes are adding version IDs at the same time, one overwriting the other's data.

Instead of the above, in MongoDB I would use [$push](https://docs.mongodb.com/manual/reference/operator/update/push/) to append to the processed list. Is there something similar in Datastore? Or do I need to change my model to use a different structure?

**Comment by dhermes** [comment]
@jmgirven This is because you want the `put` to be transactional with the read. Instead I'd recommend:

```python
with ds.transaction() as txn:
    entity_txn = ds.get(entity.key)
    entity_txn['processed'].append(version_id)
    txn.put(entity_txn)
```

so that the read and write happen transactionally.

I am going to close this since my answer seems to solve your issue. Also, I appreciate you stopping by here, but this issue tracker is more for bugs / feature requests / reports rather than Q&A. Instead I'd recommend places where people are experts on the Cloud Datastore API (rather than on this particular client code):

- https://cloud.google.com/support/docs/issue-trackers
- https://issuetracker.google.com/savedsearches/559768
- https://issuetracker.google.com/issues/new?component=187197&template=1011242
- https://groups.google.com/forum/#!forum/gcd-discuss
- https://stackoverflow.com/questions/tagged/google-cloud-datastore
