### ISSUE TITLE
ACCURACY COMPARISON

### ISSUE THREAD

**Issue by The-Gupta** [GoogleCloudPlatform/google-cloud-python#4391]
I'm new to Speech Recognition. Didn't try much and have never followed before. I need suggestions to decide which Library (Open Source) or API (like Google Speech or Microsoft's) to use.

Could any compare the performance of CMU Sphinx (with fine tune), Kaldi, autosub ([https://github.com/agermanidis/autosub](url)) wrt Google Speech API in terms of WER (word error rate)?!

Also, if you could mention the compatibility and ease of setting up with Python2/3 and on Windows, would work offline/online and is free or proprietary.

**Comment by dhermes** [comment]
@The-Gupta It sounds like you want to analyze the service, not this library.

Here is the documentation for the service itself: https://cloud.google.com/speech/

None of the maintainers of this library have particularly deep knowledge of the service beyond the API.

----

- This library **only** works online (it talks to a service offered by Google).
- This library is not OS dependent (i.e. works fine on Python)
- This library supports Python 2.7, 3.4, 3.5 and 3.6

----

I am going to close this issue since I have (hopefully) answered your question. Feel free to ask follow up questions, but I don't think we'll be able to help much.

**Comment by The-Gupta** [comment]
What would you suggest I shall do - ask on Reddit or where else?

**Comment by dhermes** [comment]
https://cloud.google.com/speech/docs/support may be helpful
