### ISSUE TITLE
BigQuery: 'properties' parameter in google.cloud.bigquery.client.Client.update_table is not documented

### ISSUE THREAD

**Issue by dmho418** [GoogleCloudPlatform/google-cloud-python#4452]
'properties' parameter in google.cloud.bigquery.client.Client.update_table is not documented.
The body of the description is also inaccurate as it always does a PATCH request.
See: https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/reference.html#google.cloud.bigquery.client.Client.update_table

**Comment by dhermes** [comment]
ASIDE: Our `pylint` configuration used to make sure `Args` matched the inputs.

**Comment by tswast** [comment]
Thanks for the report. You're absolutely right that we missed updating the docs for this method.

The way the properties parameter is used is as a list of strings, as is used in the `fields` parameter of [`update_dataset`](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/reference.html#google.cloud.bigquery.client.Client.update_dataset)

We should probably choose consistent names between `update_dataset` and `update_table` for this, too. Since we've already put people through a lot of breaking changes, I propose we deprecate `properties` for one version and remove it later.
