### ISSUE TITLE
Datastore: can't filter a query on list.

### ISSUE THREAD

**Issue by masonlouchart** [GoogleCloudPlatform/google-cloud-python#4478]
The expressions `IN` and `!=` should be allowed.

<img width="840" alt="capture d ecran 2017-11-29 a 12 19 00" src="https://user-images.githubusercontent.com/2325091/33372842-b90e96ac-d4ff-11e7-97a2-3ca43a0a207e.png">

__Versions__
_macOS High Sierra 10.13.1
Python 2.7.14
google-cloud 0.30.0
google-cloud-datastore 1.4.0_

**Comment by dhermes** [comment]
@masonlouchart Unfortunately this is not supported by the datastore API. Our client can only offer features supported by the backend.

The backend team has an issue tracker and there is a specific issue for this: https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/36

However, it's unclear if this feature will be supported.

Sorry we can't offer more. I'm going to close this issue since we can't resolve it beyond this explanation. Do let us know if you have any other issues.
