### ISSUE TITLE
BigQuery _TABLE_SUFFIX for ga_sessions

### ISSUE THREAD

**Issue by Pistolera** [GoogleCloudPlatform/google-cloud-python#4609]
This query works fine...

```
SELECT page.* FROM `zentinel-datawarehouse.xxx.ga_sessions_20170601` ga,
UNNEST (hits) hits,
UNNEST (hits.page) page
```

but when i need use `_table_suffix`

```
SELECT page.* FROM `zentinel-datawarehouse.xxx.ga_sessions_*` ga,
UNNEST (hits) hits,
UNNEST (hits.page) page
WHERE _TABLE_SUFFIX>=20170601
```

Dont works any more...
This happened in thats date because hits.page is record repeteabled... in month 08 or 09 works fine because is record NULL
ANY IDEA???

REGARDS

**Comment by tswast** [comment]
This doesn't seem like a client library issue. You may have better results asking on Stack Overflow.

**Comment by Pistolera** [comment]
But if i see a difference between one and another day hits.page (RECORD,REPETEABLE) in 20170703 and (RECORD,NULLEABLE) in 20170705....and the same query dont works, and i cant see any select.... 
I thinks exists some error... 
Sorry for my english..

regards

**Comment by tswast** [comment]
It sounds like what you're saying is that the schema changed as some point (probably on 2017-07-04) so that the `hits.page` column is now nullable instead of a repeated field. Am I understanding you correctly?

Since the table names are `ga_sessions_*`, does that mean these tables are coming from Google Analytics 360? You probably want to reach out to your sales person / support contact for Google Analytics to report this issue.
