### ISSUE TITLE
GRPC_LINUX_EPOLL is not defined

### ISSUE THREAD

**Issue by arindamchoudhury** [GoogleCloudPlatform/google-cloud-python#4650]
Hi,
I am using 
google-cloud-pubsub==0.30.0
grpcio==1.8.2

Whenever I instanciate a PublisherClient, I am getting these messages:
E1221 13:17:26.610316777       9 ev_epollex_linux.cc:1482]   Skipping epollex becuase GRPC_LINUX_EPOLL is not defined.
E1221 13:17:26.610714403       9 ev_epoll1_linux.cc:1261]    Skipping epoll1 becuase GRPC_LINUX_EPOLL is not defined.
E1221 13:17:26.610820117       9 ev_epollsig_linux.cc:1761]  Skipping epollsig becuase GRPC_LINUX_EPOLL is not defined.

Thanks,

**Comment by dhermes** [comment]
@arindamchoudhury Thanks for reporting. These are not a sign of any error, just stray logging statements that "escape" from the `grpcio` package (which is how our clients "speak gRPC").

I am going to close this issue, since there isn't anything we can do in `google-cloud-python`. I have filed https://github.com/grpc/grpc/issues/13855 to notify the `grpcio` team. Feel free to follow that issue and comment there if you like.

**Comment by nickatnight** [comment]
@dhermes I think the grpc team fixed that bug. Are you able to update this package with a fix?

**Comment by tseaver** [comment]
@nickatnight Could you submit a PR which bumps the dependency to `grpcio >= 1.8.3` in `api_core/setup.py` and `core/setup.py`?

**Comment by dhermes** [comment]
@nickatnight If you want a fix, simply `pip install --upgrade 'grpcio >= 1.8.3'`.

This is only a stray logging message, not a sign of any bug, so there is no need to release a fix that requires `>= 1.8.3` (we currently [require][1] `>= 1.8.2`)

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/155343ada7db9f5585bf0932f7fa4e7b128d6871/api_core/setup.py#L66

**Comment by nickatnight** [comment]
@dhermes @tseaver That's good enough for me 👍  Thanks
