### ISSUE TITLE
BigQuery: client documentation, incorrect create

### ISSUE THREAD

**Issue by yiga2** [GoogleCloudPlatform/google-cloud-python#4725]
Documentation issue on https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/usage.html (and https://github.com/GoogleCloudPlatform/google-cloud-python/blob/63b7245699510259f584bc3ca328a72af8c2120f/docs/bigquery/snippets.py)

> job_config.create_disposition = 'NEVER'

should be **CREATE_NEVER**. Could not determine that NEVER was an alias. If it is, should be documented

**Comment by tseaver** [comment]
@yiga2 Thanks for the report!  In fact, we have class constants for that string (and the others) -- I would argue that we should expose those classes at the top-level, and use them in all our docs, rather than string literals:

- `google.cloud.bigquery.job.Compression`
- `google.cloud.bigquery.job.CreateDisposition`
- `google.cloud.bigquery.job.DestinationFormat`
- `google.cloud.bigquery.job.Encoding`
- `google.cloud.bigquery.job.QueryPriority`
- `google.cloud.bigquery.job.SourceFormat`
- `google.cloud.bigquery.job.WriteDisposition`

**Comment by yiga2** [comment]
Agreed. Encouraging the use of constants would reduce risk of typos

**Comment by chemelnucfin** [comment]
I believe this issue has been fixed and is now superseded by #4793.
Please reopen if I'm wrong @tswast.

**Comment by tswast** [comment]
Well, not fixed. But #4793 is indeed a duplicate.
