### ISSUE TITLE
BigQuery - AttributeError: 'module' object has no attribute 'SourceFormat'

### ISSUE THREAD

**Issue by snehashirsat** [GoogleCloudPlatform/google-cloud-python#5089]
Hi, I am using BigQuery API : bigquery.SourceFormat.PARQUET to load parquet data from GCS to BigQuery table.

At line:
    job_config = bigquery.LoadJobConfig()
    job_config.source_format = bigquery.SourceFormat.PARQUET

it throws an error - 
   AttributeError: 'module' object has no attribute 'SourceFormat'

Environment specs are here:
Python 2.7.10
Name: google-cloud
Version: 0.32.0
Summary: API Client library for Google Cloud
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: googleapis-publisher@google.com
License: Apache 2.0

OS and version
ProductName:	Mac OS X
ProductVersion:	10.12.6

Code example:
```
def test_load_table_from_uri_parquet():
    # [START bigquery_load_table_gcs_parquet]
    client = bigquery.Client()
    dataset_id = 'dataset_01'
    dataset_ref = client.dataset(dataset_id)
    job_config = bigquery.LoadJobConfig()
    job_config.source_format = bigquery.SourceFormat.PARQUET
    load_job = client.load_table_from_uri(
        'gs://xxxx/xxx/*.parquet',
        dataset_ref.table('tablexxx'),
        job_config=job_config)
    assert load_job.job_type == 'load'
```

**Comment by chemelnucfin** [comment]
@jonparrott so release-0.31.0 tag points to 0.28.1, I don't think I'll bother fixing that since when we have newer versions it won't be a big deal..
[rename tag](https://stackoverflow.com/questions/1028649/how-do-you-rename-a-git-tag)
71d4adb... Release 0.28.1 (#4953)

31.0 should be [here](https://github.com/GoogleCloudPlatform/google-cloud-python/commit/cd9b89ead0be95827c9eac5a9a8c5d8fdaee3cae)

But that doesn't have the SourceFormat also.  
So we will need a new release for BigQuery.
Are we going to 1.0.0 this?  How do I run releasetool or should I go back to using my script?

@snehashirsat It is probably better to install google-cloud-bigquery, and when we have a new release, this problem should be fixed.

**Comment by snehashirsat** [comment]
already have google-cloud-bigquery version 
`
Name: google-cloud-bigquery
Version: 0.31.0
Summary: Google BigQuery API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
`
will have to wait for 0.32.0

**Comment by chemelnucfin** [comment]
If you are only toying with it, you should be able to replace `bigquery.SourceFormat.PARQUET` with `'PARQUET'`.  See [here](https://github.com/GoogleCloudPlatform/google-cloud-python/commit/6e85c95ab9eb635a2f62f572c8bcbcee972155ba)

It is just a convenient alias, but we do suggest using the constant when it becomes available.

**Comment by tseaver** [comment]
Closing, given that the constant exists / will be available in the next release.

**Comment by chemelnucfin** [comment]
BigQuery 0.32.0 is now available.  Please feel free (and suggested) to use the new constant.
