### ISSUE TITLE
Subscriber eating errors

### ISSUE THREAD

**Issue by dmsolow** [GoogleCloudPlatform/google-cloud-python#5198]
I recently upgraded to google-cloud-pubsub 0.33.1 and it looks like `future.result()` is not raising callback exceptions how it used to. Here's the code I'm using:
```python
from google.cloud import pubsub_v1
from concurrent.futures import ThreadPoolExecutor

subscriber = pubsub_v1.SubscriberClient()
flow_control = pubsub_v1.types.FlowControl() 
subscription_path = subscriber.subscription_path('project.name', 'sub.name')
executor = ThreadPoolExecutor(max_workers=1)
policy = pubsub_v1.subscriber.policy.thread.Policy(
    subscriber, subscription_path, executor=executor, flow_control=flow_control
)     

def callback(message):
    print('got message:', message)
    raise ValueError('test')

future = policy.open(callback)
while True:
    print('Start of error loop')
    try:
        future.result()
    except KeyboardInterrupt:
        print('Got interrupt, exiting!')
        break
    except Exception as e:
        print('Got uncaught error in callback!')
        print(e)

policy.close()
```

As you can see, `callback` raises a ValueError after printing the message. However, the `future.result` call in the `try` block never raises this exception. Any idea how to get this error?

**Comment by jonparrott** [comment]
The `future.result` from `policy.open`/`subscriber.subscribe` only resolves when the *stream* is closed. It does not resolve when the callback is executed. The callbacks are executed by a ` `ThreadPoolExecutor` that is resilient in the face of exceptions thrown by the callback (so that poorly behaved callbacks do not cause the system to crash). If you need to handle errors in your callback, you will need to add the `try:... catch:` logic there.
