### ISSUE TITLE
Snippet in documentation is not correct.

### ISSUE THREAD

**Issue by allsyed** [GoogleCloudPlatform/google-cloud-python#5344]
Code snippet on [PubSub index page](https://google-cloud-python.readthedocs.io/en/latest/pubsub/index.html#subscribing):

```python
def callback(message):
    print(message.data)
    message.ack()
future = subscriber.subscribe(subscription_name, callback)
```
But, subscribe returns a `Policy` instance not `future`. 

```python
def callback(message):
    print(message.data)
    message.ack()
policy = subscriber.subscribe(subscription_name, callback)
future = policy.future
```

Is more appropriate

**Comment by tseaver** [comment]
@allsyed The docs for the `/latest` tree track the master branch, where `subscribe` *does* [return a future](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/4cea94970a13590f9b79ecc278606e72ff529c8e/pubsub/google/cloud/pubsub_v1/subscriber/client.py#L170-L174) since 0da12f692070258b652d8a807a5f00c44bdbe618.
