### ISSUE TITLE
Weird Error- get() expected a dict or protobuf message, got <class 'list'>.

### ISSUE THREAD

**Issue by bionichuman** [GoogleCloudPlatform/google-cloud-python#5395]
Hi, I keep getting this error with this code- 

get() expected a dict or protobuf message, got <class 'list'>.

![actuallerrrrr](https://user-images.githubusercontent.com/11791504/40577919-21d040d0-60da-11e8-93db-2aa89f784c16.JPG)

How do I fix this?

**Comment by tseaver** [comment]
Can you please provide a gist of the code you are using?

**Comment by bionichuman** [comment]
@tseaver Here is the code.
https://pastebin.com/BZ9PMXw5

**Comment by tseaver** [comment]
In line 274, you create a list with one item, which is the `Image` protobuf you should be passing (instead of the list) in line 277.

Note that this would be a lot easier to debug if you weren't capturing and swallowing the original error (line 292):  the traceback would have showed you the line in your code which triggered the error.
