### ISSUE TITLE
Image text Recognition using Keras in Python

### ISSUE THREAD

**Issue by vashish76** [GoogleCloudPlatform/google-cloud-python#5768]
Use case is to recognize the text and digits from the attached image using Machine / Deep learning technique such as Keras tenserflow in Python

My questions are the following..
1. Whether I need to make use of MNIST database for digit recognition if so then which database that can be used for text recognition. Do i need to build two different models ?
2. Once model is trained then I will validate the model on my data of image files ? 
3. What is the input to the keras model.. Will it be a raw image or the pixel values ?

Appreciate if you could provide some guidance on the above

![r001](https://user-images.githubusercontent.com/42150716/43785549-307ae32c-9a84-11e8-91b8-e981482144bd.JPG)

**Comment by tseaver** [comment]
@vashish76 Thanks for your question.  Unfortunately, this repository is about maintaining the Python client libraries for Google Cloud APIs (`google-cloud-vision` and / or `google-cloud-automl`, in your case), rather than for support of the APIs themselves.

Please investigate the following support links for the two APIs:

- [Cloud Vision Support](https://cloud.google.com/vision/docs/support)
- [AutoML VIsion Support](https://cloud.google.com/vision/automl/support)
