### ISSUE TITLE
BigTable: google-cloud-bigtable 0.30.0 throws InvalidChunk error while iterating through a large collection

### ISSUE THREAD

**Issue by xEcEz** [GoogleCloudPlatform/google-cloud-python#5876]
Python version: 3.6.3
google-cloud-bigtable 0.30.0

After switching to 0.30.0 and adapting my code to use the newly integrated iter function of PartialRowsData, I can't iterate through a large collection without the InvalidChunk error being thrown.

Sample code:
```
rows = table.read_rows()
for r in row:
...
```

**Comment by tseaver** [comment]
@xEcEz Can you please provide the full traceback?  Also, can you guesstimate the size of the table (number of rows, column families, etc.)?

**Comment by xEcEz** [comment]
Stacktrace:
```
at _validate_cell_data_new_row (/usr/lib/python3.6/site-packages/google/cloud/bigtable/row_data.py:517)
at _validate_cell_data (/usr/lib/python3.6/site-packages/google/cloud/bigtable/row_data.py:505)
at __iter__ (/usr/lib/python3.6/site-packages/google/cloud/bigtable/row_data.py:474)
at readAll (/scripts/bigtable_manager.py:106)
at call (/usr/lib/python3.6/site-packages/tenacity/__init__.py:361)
at __get_result (/usr/lib/python3.6/concurrent/futures/_base.py:384)
at result (/usr/lib/python3.6/concurrent/futures/_base.py:425)
at reraise (/usr/lib/python3.6/site-packages/tenacity/__init__.py:167)
at iter (/usr/lib/python3.6/site-packages/tenacity/__init__.py:331)
at call (/usr/lib/python3.6/site-packages/tenacity/__init__.py:358)
at wrapped_f (/usr/lib/python3.6/site-packages/tenacity/__init__.py:292)
at retryHandler (/scripts/bigtable_manager.py:149)
at getAllRanksTiers (/scripts/bigtable_manager.py:268)
at run (/scripts/queue_processor_update.py:68)
at _bootstrap (/usr/lib/python3.6/multiprocessing/process.py:258)
```

Table size: 2.5M approx.

**Comment by sduskis** [comment]
@AVaksman, can you please take a look at this?

**Comment by sduskis** [comment]
I've been looking at this.  `row_data.py:517` indicates that the client sees row_keys that are out of order. 
 v0.29.0 and before didn't have that validation.

We can relax the validation in the short term, but it really ought to be fixed.  The service doesn't send rows out of sequence, so my guess is that there's some sort of unexpected retry that happens that restarts the request from the beginning.  

I'm going to run a long test over the week end to see if I can reproduce the problem.  I'm also going to do some refactoring of [`row_data.py`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigtable/google/cloud/bigtable/row_data.py) so that I can better rationalize about it a bit more.

**Comment by zunger-humu** [comment]
I've had this issue show up and stably happen at a single row. I'm guessing that was a tablet boundary, which may give some clues as to the origin. (Unfortunately, that table has changed a lot since then, so I can't recheck and see if this was a time-transient error -- suggesting something retry-associated -- or not)

**Comment by sduskis** [comment]
I'm going to remove this check for now.  I wonder if this issue relates to the fact that Cloud Bigtable has binary data, and `<=` checks may not be accurate due to some kind of encoding issue, or difference between Python and Cloud Bigtable's implementation.

**Comment by sduskis** [comment]
Ugh.  `'C' <= 'f'`, which is true for non-strings, but not necessarily for the way .  We'll need a Python equivalent of this Java class: [ByteStringComparator](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/edc800c1c7f188f4cc70c5746c80cb67de0d4df3/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/util/ByteStringComparator.java).

**Comment by zunger-humu** [comment]
Not necessarily for the way?

**Comment by sduskis** [comment]
@zunger-humu, I updated the comment...

**Comment by sduskis** [comment]
ok.  'C' is actually less than 'f' in ascii, so '<=' ought to work correctly for ascii.

**Comment by sduskis** [comment]
I raised an internal issue to see if there's anything else going on.

**Comment by zunger-humu** [comment]
More data: I just (accidentally) had some code running on 0.30 instead of
0.29, where it was doing a read_rows over about 2700 rows of data. If it
just did the read_rows, everything was fine, but if the read_rows was
intermixed with a mutate operation (batched, but getting several batches
off before things went wrong) the read would stop after 274 rows, with no
error or sign that anything was less than perfect. The row keys in this
case were all 16 byte hex expressed as ASCII, so they should be super-nice
from a code perspective.

I have no idea what's going on here but 0.30 is very scary. If one of our
partner experience people hadn't noticed that a certain output file had way
fewer entries than it was supposed to, we would have just messed up some
user data...

**Comment by sduskis** [comment]
@AVaksman reproduced the problem with a request of reading the entire table (i.e. None start/end).  Our retry logic doesn't properly handle that situation.  A PR is coming shortly.

**Comment by sduskis** [comment]
@zunger-humu and @xEcEz, we were able to reproduce the problem relating to full table reads (i.e. not specifying start/end).  Did you set start / end in your applications, or did you read the full table?

**Comment by zunger-humu** [comment]
I believe that in all the cases where this bug triggered, it was scanning
all rows.

**Comment by xEcEz** [comment]
@sduskis It happened during full table reads.

**Comment by zunger-humu** [comment]
Awesome -- thank you!

Is this going to be released as a fixed version of 0.30?

**Comment by sduskis** [comment]
@zunger-humu, I just submitted #5997 to create a 0.30.2 version.

**Comment by zunger-humu** [comment]
You rock. :)

**Comment by xEcEz** [comment]
I am still having issues with this. 

To give you a bit of context, I am running a data fetching task on the Google Kubernetes Engine where I load a list of ids to handle from BigTable, using the same code snippet I posted previously. Running from my machine, I can scan the entire table without providing a start/end key, but if I don't provide them on the GKE, an error is thrown at some point. Also, the error isn't always the same, as I sometimes get the InvalidChunk error discussed here, but sometimes get the following grpc error:

status = StatusCode.INTERNAL
details = "Received RST_STREAM with error code 2"
debug_error_string = "{"created":"@1537796211.884939078","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}"

Any idea where this might come from?

**Comment by sduskis** [comment]
@xEcEz, can you please create a new issue for the RST_STREAM? That's caused by a different problem.
