### ISSUE TITLE
Spanner: database.transaction() does not work anymore

### ISSUE THREAD

**Issue by wawrencelu** [GoogleCloudPlatform/google-cloud-python#6029]
Hi, the docs state that I can start a transaction like so: https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/transaction-usage.html#use-a-transaction-as-a-context-manager

```
with database.transaction() as transaction:
```

However, when I call it I receive an error saying that `transaction` attribute does not exist on the database object. Looking at the source, it looks like that method no longer exists either.

Why was it removed? Can we re-add it? Happy to submit a patch to do so.

**Comment by tseaver** [comment]
@wawrencelu a `Transaction` instance is bound to a `Session`, not to the `Database`.  We should just remove any mention of `Database.transaction()` from the docs, and show it as being used from within a session instead.

Or we could just remove the examples which show manual use of the `Transaction`:  the preferred mode is to use `Database.run_in_transaction()`, because it handles the complicated retry-on-abort logic.  @snehashah16, which would you prefer?

**Comment by snehashah16** [comment]
Sure, we can reference all docs (all mentions) to point to `Database.run_in_transaction()`

hopefully there are useful snippets on the manual usage just if a specific usecase exists

**Comment by tseaver** [comment]
@snehashah16 #6032 leaves the manual snippets in place, but sets them off with notes pointing to `run_in_transaction`.
