### ISSUE TITLE
Create DNS zone change from a bind zone file (or string)

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#76]

**Comment by tseaver** [comment]
(Assuming we get past the parsing issue, which is a bit gnarly)

We can't create the `Changes` instance directly from a file / string:  we have to have the existing resource record set, from which we would generate `additions` and `deletions`.  E.g., convert the existng set to a list of tuples:

```python
from gcloud.dns import Client
from gcloud.dns.changes import Changes
from gcloud.dns.resource_record_set import ResourceRecordSet
client = Client()
zone = client.zone('example.com')
rrs, token = zone.list_resource_record_sets()
assert token is None  # see below
current = set([(rr.name, rr.type, rr.ttl, tuple(rr.rrdatas)) for rr in rrs])
# hypothetical utility function returning an equivalent set of tuples
updated = parse_bind_config(file_or_string)
changes = Changes(zone)
for deleted in current - updated:
    changes.delete_record_set(*deleted)
for added in updated - current:
    changes.add_record_set(*deleted)
changes.create()  # API call
```

The problem is compounded for large-enough zones that all resource record sets cannot be retrieved in a single request:  at that point, we have no consistency guarantees between separate "pages" that we fetch, which makes generating a "diff" much harder.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
